I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 231, in script
    show mc neutral at portait
  File "game/script.rpy", line 231, in <module>
    show mc neutral at portait
NameError: name 'portait' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 231, in script
    show mc neutral at portait
  File "/Users/noelkim/Downloads/renpy-8.3.4-sdk/renpy/ast.py", line 1117, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Users/noelkim/Downloads/renpy-8.3.4-sdk/renpy/ast.py", line 1076, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "/Users/noelkim/Downloads/renpy-8.3.4-sdk/renpy/ast.py", line 1076, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "/Users/noelkim/Downloads/renpy-8.3.4-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/noelkim/Downloads/renpy-8.3.4-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 231, in <module>
    show mc neutral at portait
NameError: name 'portait' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.3.4.24120703
WIREDMIND 1.0
Tue Jul  1 01:49:23 2025
